apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aecontrol
resources:
  - ../../kubernetes
  - cluster.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: postgres
  - target:
      version: v1
      kind: Service
      name: postgres
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: aecontrol-postgres-app
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/key
        value: uri
images:
  - name: ghcr.io/jeremydemers/agent-eval-control-plane
    newTag: 0.45.0
