apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aecontrol-kata-runtimeclass-reader
rules:
  - apiGroups: [node.k8s.io]
    resources: [runtimeclasses]
    resourceNames: [kata-qemu]
    verbs: [get]
