apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aecontrol
resources:
  - primary-archive.yaml
  - secondary-archive.yaml
  - secondary-cluster.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
images:
  - name: ghcr.io/jeremydemers/agent-eval-control-plane
    newTag: 0.49.0
