apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aecontrol-postgres-promoter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aecontrol-postgres-promoter
subjects:
  - kind: ServiceAccount
    name: aecontrol-postgres-promoter
