apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aecontrol
resources:
  - ../cloudnative-pg
  - object-store.yaml
  - scheduled-backup.yaml
patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: aecontrol-postgres
    patch: |-
      - op: add
        path: /spec/plugins
        value:
          - name: barman-cloud.cloudnative-pg.io
            isWALArchiver: true
            parameters:
              barmanObjectName: aecontrol-postgres-backup
images:
  - name: ghcr.io/jeremydemers/agent-eval-control-plane
    newTag: 0.50.0
